include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at:
# https://dart.dev/guides/language/analysis-options
analyzer:
  exclude:
    - 'lib/**/*.g.dart'
    - 'lib/**/*.freezed.dart'
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    avoid_print: info
    prefer_single_quotes: warning

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart.dev/tools/linter-rules.
  rules:
    # Example of how to disable a lint rule
    # avoid_print: false

    # Example of how to enable an additional lint rule
    # prefer_single_quotes: true
